twig:
    default_path: '%kernel.project_dir%/templates'
    # Make Symfony write convenient html output for Bootstrap
    form_themes:
        - bootstrap_4_horizontal_layout.html.twig # Same line
        #- bootstrap_4_layout.html.twig # widget bellow the label

when@test:
    twig:
        strict_variables: true
